SoltuionSalesSystem/SalesSystem.WebApplication/Controllers/NegocioController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using Newtonsoft.Json;
using SalesSystem.WebApplication.Models.ViewModels;
using SalesSystem.WebApplication.Utilidades.Response;
using SalesSystem.BLL.Interfaces;
using SalesSystem.Entity;
using Microsoft.AspNetCore.Authorization;

namespace SalesSystem.WebApplication.Controllers
{
	[Authorize]
	public class NegocioController : Controller
    {
        private readonly IMapper _mapper;
        private readonly INegocioService _negocioService;

        public NegocioController(IMapper mapper, INegocioService negocioService)
        {
            _mapper = mapper;
			_negocioService = negocioService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
		public async  Task<IActionResult> Obtener()
		{
            GenericResponse<VMNegocio> gResponse = new GenericResponse<VMNegocio>();

            try
            {
                VMNegocio vmNegocio = _mapper.Map<VMNegocio>(await _negocioService.Obtener());
                gResponse.Estado = true;
                gResponse.Objeto = vmNegocio;

			}
            catch (Exception ex)
            {
				gResponse.Estado = false;
				gResponse.Mensaje = ex.Message;
			}

            return StatusCode(StatusCodes.Status200OK, gResponse);
			
		}

		[HttpPost]
		public async Task<IActionResult> GuardarCambios([FromForm] IFormFile logo, [FromForm] string modelo)
		{
			GenericResponse<VMNegocio> gResponse = new GenericResponse<VMNegocio>();

			try
			{
				VMNegocio vmNegocio = JsonConvert.DeserializeObject<VMNegocio>(modelo);

				string nombreLogo = "";
				Stream logoStream = null;

				if (logo != null)
				{
					string nombre_en_codigo = Guid.NewGuid().ToString("N");
					string extension = Path.GetExtension(logo.FileName);
					nombreLogo = string.Concat(nombre_en_codigo, extension);
					logoStream = logo.OpenReadStream();
				}

				Negocio negocio_editado = await _negocioService.GuardarCambios(_mapper.Map<Negocio>(vmNegocio),logoStream, nombreLogo);

				vmNegocio = _mapper.Map<VMNegocio>(negocio_editado);

				gResponse.Estado = true;
				gResponse.Objeto = vmNegocio;

			}
			catch (Exception ex)
			{
				gResponse.Estado = false;
				gResponse.Mensaje = ex.Message;
			}

			return StatusCode(StatusCodes.Status200OK, gResponse);

		}

	}
}

SoltuionSalesSystem/SalesSystem.WebApplication/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using SalesSystem.WebApplication.Models.ViewModels;
using SalesSystem.BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace SalesSystem.WebApplication.Controllers
{
	[Authorize]
	public class ReporteController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IVentaService _ventaService;

        public ReporteController(IMapper mapper, IVentaService ventaService)
        {
            _mapper = mapper;
            _ventaService = ventaService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
		public async Task<IActionResult> ReporteVenta(string fechaInicio, string fechaFin)
		{
            List<VMReporteVenta> vmLista = _mapper.Map<List<VMReporteVenta>>( await _ventaService.Reporte( fechaInicio,  fechaFin));

            return StatusCode(StatusCodes.Status200OK, new { data = vmLista });
		}
	}
}

SoltuionSalesSystem/SalesSystem.WebApplication/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using Newtonsoft.Json;
using SalesSystem.WebApplication.Models.ViewModels;
using SalesSystem.WebApplication.Utilidades.Response;
using SalesSystem.BLL.Interfaces;
using SalesSystem.Entity;
using Microsoft.AspNetCore.Authorization;

namespace SalesSystem.WebApplication.Controllers
{
	[Authorize]
	public class UsuarioController : Controller
	{
		private readonly IUsuarioService _usuarioService;
		private readonly IRolService _rolService;
		private readonly IMapper _mapper;
		public UsuarioController(IUsuarioService usuarioService, IRolService rolService, IMapper mapper)
		{
			_usuarioService = usuarioService;
			_rolService = rolService;
			_mapper = mapper;

		}

		public IActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> ListaRoles()
		{
			List<VMRol> vmListaRoles = _mapper.Map<List<VMRol>>(await _rolService.Lista());
			return StatusCode(StatusCodes.Status200OK, vmListaRoles);
		}

		[HttpGet]
		public async Task<IActionResult> Lista()
		{
			List<VMUsuario> vmUsuarioLista = _mapper.Map<List<VMUsuario>>(await _usuarioService.Lista());
			return StatusCode(StatusCodes.Status200OK, new { data = vmUsuarioLista });
		}

		[HttpPost]
		public async Task<IActionResult> Crear([FromForm] IFormFile foto, [FromForm] string modelo)
		{
			GenericResponse<VMUsuario> gResponse = new GenericResponse<VMUsuario>();

			try
			{
				VMUsuario vmUsuario = JsonConvert.DeserializeObject<VMUsuario>(modelo);

				string nombreFoto = "";
				Stream fotoStream = null;

				if (foto != null)
				{
					string nombre_en_codigo = Guid.NewGuid().ToString("N");
					string extension = Path.GetExtension(foto.FileName);
					nombreFoto = string.Concat(nombre_en_codigo, extension);
					fotoStream = foto.OpenReadStream();
				}

				string urlPlantillaCorreo = $"{this.Request.Scheme}://{this.Request.Host}/Plantilla/EnviarClave?correo=[correo]&clave=[clave]";

				Usuario usuario_creado = await _usuarioService.Crear(_mapper.Map<Usuario>(vmUsuario), fotoStream, nombreFoto, urlPlantillaCorreo);
				vmUsuario = _mapper.Map<VMUsuario>(usuario_creado);

				gResponse.Estado = true;
				gResponse.Objeto = vmUsuario;

			}
			catch (Exception ex)
			{
				gResponse.Estado = false;
				gResponse.Mensaje = ex.Message;
			}
			return StatusCode(StatusCodes.Status200OK, gResponse);
		}


		[HttpPut]
		public async Task<IActionResult> Editar([FromForm] IFormFile foto, [FromForm] string modelo)
		{
			GenericResponse<VMUsuario> gResponse = new GenericResponse<VMUsuario>();

			try
			{
				VMUsuario vmUsuario = JsonConvert.DeserializeObject<VMUsuario>(modelo);

				string nombreFoto = "";
				Stream fotoStream = null;

				if (foto != null)
				{
					string nombre_en_codigo = Guid.NewGuid().ToString("N");
					string extension = Path.GetExtension(foto.FileName);
					nombreFoto = string.Concat(nombre_en_codigo, extension);
					fotoStream = foto.OpenReadStream();
				}

				Usuario usuario_editado = await _usuarioService.Editar(_mapper.Map<Usuario>(vmUsuario), fotoStream, nombreFoto);
				vmUsuario = _mapper.Map<VMUsuario>(usuario_editado);

				gResponse.Estado = true;
				gResponse.Objeto = vmUsuario;

			}
			catch (Exception ex)
			{
				gResponse.Estado = false;
				gResponse.Mensaje = ex.Message;
			}
			return StatusCode(StatusCodes.Status200OK, gResponse);
		}

		[HttpDelete]

		public async Task<IActionResult> Eliminar(int IdUsuario)
		{
			GenericResponse<string> gResponse = new GenericResponse<string>();

			try
			{
				gResponse.Estado = await _usuarioService.Eliminar(IdUsuario);
			}
			catch (Exception ex)
			{
				gResponse.Estado = false;
				gResponse.Mensaje = ex.Message;
			}

			return StatusCode(StatusCodes.Status200OK,gResponse);

		}

	}
}

SoltuionSalesSystem/SalesSystem.WebApplication/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using SalesSystem.WebApplication.Models.ViewModels;
using SalesSystem.WebApplication.Utilidades.Response;
using SalesSystem.BLL.Interfaces;
using SalesSystem.Entity;

using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SalesSystem.WebApplication.Controllers
{
	[Authorize]
	public class VentaController : Controller
    {
        private readonly ITipoDocumentoVentaService _tipoDocumentoVentaService;
        private readonly IVentaService _ventaService;
        private readonly IMapper _mapper;
		private readonly IConverter _converter;

        public VentaController(ITipoDocumentoVentaService tipoDocumentoVentaService, IVentaService ventaService, IMapper mapper, IConverter converter)
        {
            _tipoDocumentoVentaService = tipoDocumentoVentaService;
            _ventaService = ventaService;
            _mapper = mapper;
			_converter = converter;

		}

        public IActionResult NuevaVenta()
        {
            return View();
        }

		public IActionResult HistorialVenta()
		{
			return View();
		}

        [HttpGet]
		public async Task<IActionResult> ListaTipoDocumentoVenta()
		{
            List<VMTipoDocumentoVenta> vmListaTipoDocumento = _mapper.Map<List<VMTipoDocumentoVenta>>(await _tipoDocumentoVentaService.Lista());
            return StatusCode(StatusCodes.Status200OK, vmListaTipoDocumento);
		}

		[HttpGet]
		public async Task<IActionResult> ObtenerProductos(string busqueda)
		{
            List<VMProducto> vmListaProductos = _mapper.Map<List<VMProducto>>(await _ventaService.ObtenerProductos(busqueda));
			return StatusCode(StatusCodes.Status200OK, vmListaProductos);
		}

		[HttpPost]
		public async Task<IActionResult> RegistrarVenta([FromBody] VMVenta modelo)
		{
			GenericResponse<VMVenta> gResposne = new GenericResponse<VMVenta>();

			try
			{

				ClaimsPrincipal claimUser = HttpContext.User;

				string idUsuario = claimUser.Claims
											.Where(c => c.Type == ClaimTypes.NameIdentifier)
											.Select(c => c.Value).SingleOrDefault();
				modelo.IdUsuario = int.Parse(idUsuario);

				Venta venta_creada = await _ventaService.Registrar(_mapper.Map<Venta>(modelo));
				modelo = _mapper.Map<VMVenta>(venta_creada);

				gResposne.Estado = true;
				gResposne.Objeto = modelo;

			}
			catch (Exception ex)
			{
				gResposne.Estado = false;
				gResposne.Mensaje = ex.Message;
			}

			return StatusCode(StatusCodes.Status200OK, gResposne);
		}

		[HttpGet]
		public async Task<IActionResult> Historial(string numeroVenta, string fechaInicio, string fechaFin)
		{
			List<VMVenta> vmHistorialVenta = _mapper.Map<List<VMVenta>>(await _ventaService.Historial(numeroVenta,fechaInicio,fechaFin));
			return StatusCode(StatusCodes.Status200OK, vmHistorialVenta);
		}

		public IActionResult MostrarPDFVenta (string numeroVenta)
		{
			string urlPlantillaVista = $"{this.Request.Scheme}://{this.Request.Host}/Plantilla/PDFVenta?numeroVenta={numeroVenta}";

			var pdf = new HtmlToPdfDocument()
			{
				GlobalSettings = new GlobalSettings()
				{
					PaperSize = PaperKind.A4,
					Orientation = Orientation.Portrait,
				},
				Objects =
				{
					new ObjectSettings()
					{
						Page = urlPlantillaVista
					}
				}
			};

			var archivoPDF = _converter.Convert(pdf);
			return File(archivoPDF, "application/pdf");

		}

	}
}

SoltuionSalesSystem/SalesSystem.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mi Tienda - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            @await Component.InvokeAsync("Menu")
            <!-- Nav Item - Dashboard -->
         @*   <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>*@

            <!-- Nav Item - Administración Collapse Menu -->
          @*  <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Usuario")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("Index","Negocio")">Negocio</a>
                    </div>
                </div>
            </li>*@

            <!-- Nav Item - Inventario Collapse Menu -->
         @*   <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Categoria")">Categorias</a>
                        <a class="collapse-item" href="@Url.Action("Index","Producto")">Productos</a>
                    </div>
                </div>
            </li>*@

            <!-- Nav Item - Venta Collapse Menu -->
         @*   <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Ventas</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevaVenta","Venta")">Nueva Venta</a>
                        <a class="collapse-item" href="@Url.Action("HistorialVenta","Venta")">Historial Venta</a>
                    </div>
                </div>
            </li>*@

            <!-- Nav Item - Reportes Collapse Menu -->
          @*  <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Reporte")">Reporte de Ventas</a>
                    </div>
                </div>
            </li>*@

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                     @*   <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("Perfil","Home")">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>*@

                        @await Component.InvokeAsync("MenuUsuario")

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>